python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
python test_dmmo_lat.py
cat test_dmmo_lat.py >> 'modele-gpu.log'
